### ISSUE TITLE
ImportError: No module named 'django_markdown'

### ISSUE THREAD

**Issue by raratiru** [sv0/django-markdown-app#1]
Hallo,

Thank you for creating this application.

After inserting `django_markdown` to installed apps, I receive the error:

`ImportError: No module named 'django_markdown'`

I am using `Django 1.9.9` on `Python 3.4.2` and:

```
$ pip freeze
...
django-markdown-app==0.8.6
django-markdown-deux==1.0.5
Markdown==2.6.6
markdown2==2.3.1

```

**Comment by sv0** [comment]
I  can't reproduce this bug.

**Comment by raratiru** [comment]
OK ... I will try in a fresh install. I will reopen if needed,
