### ISSUE TITLE
9.3.1 doesn't support multiple markdown fields in admin.

### ISSUE THREAD

**Issue by Cediddi** [sv0/django-markdown-app#17]
Interesting problem I've found is, If I have multiple markdown fields in my model and thus in my admin, only the first field will have the editor initialized. There's multiple jsons embedded in the html with the same id which is the main problem. Also because I have multiple markdown fields in the admin, webpage tries to load same js file over and over too. This was not the case in 0.9.2 but you removed that version from pypi and my production servers are having serious issues right now. I can't deploy any new server with 0.9.2 and 0.9.3.1 breaks the admin. What should I do?

**Comment by sv0** [comment]
Hey man,
I'll check it out and let you know.

**Comment by sv0** [comment]
@Cediddi 
I do not know what Django version you do use in your project.
The bug you writes about was fixed by @rspeed in  commit 4a53b1330ee2

If you need ver 0.9.2, you can still install it using direct link to ver 0.9.2:

    pip install -e git+https://github.com/sv0/django-markdown-app.git@0.9.2#egg=django_markdown_app

**Comment by Cediddi** [comment]
I'm using 1.11.x For a quick fix I did that install from git trick. I'll
send a better log in a few hours.
