### ISSUE TITLE
Preview is not available on clicking preview button of markdown fieild in django-admin interface

### ISSUE THREAD

**Issue by ialihaider75** [sv0/django-markdown-app#22]
Following error comes up on the console window when clicking preview button of the markdown field.
**POST 127.0.0.1:8000/markdown/preview 403 (Forbidden)**
I think this is because of csrf token missing in the implementation of the post method of function which triggers on the preview button click.

Please fix this issue.

**Comment by sv0** [comment]
Please feel free to fix it and create a pull request.

**Comment by Alihaider122** [comment]
If I was able to make changes then why would I open an issue here for help?

Please help me.

**Comment by ialihaider75** [comment]
> Please feel free to fix it and create a pull request.

If I was able to make changes then why would I open an issue here for help?

Please help me.

**Comment by gregschmit** [comment]
@Alihaider122 That was a polite way of saying "were busy with life, jobs, and other projects, and are unlikely to get to this, but since it's an open source project, you're welcome to contribute."
