### ISSUE TITLE
Error with Django 1.11

### ISSUE THREAD

**Issue by larubbio** [sv0/django-markdown-app#7]
With 1.11 I get the error "context must be a dict rather than Context."

According to the [release notes](https://docs.djangoproject.com/en/1.11/releases/1.11/#django-template-render-prohibits-non-dict-context) templates no longer accept Context objects:

Changing django_markdown/utils.py line 48 from:

>     ctx = Context(dict(
>        selector=selector, extra_settings=simplejson.dumps(options)),
>       autoescape=False)

to

>    ctx = dict(selector=selector, extra_settings=simplejson.dumps(options))

Seems to resolve the error.

**Comment by sv0** [comment]
Thank you, Rob.
I've added your fix in commit a65456be14b
